### ISSUE TITLE
Select box list opens in a new browser window

### ISSUE THREAD

**Issue by sap-nocops** [ubports/morph-browser#54]
- Device: one plus one
- Channel: 16.04 Stable
- build: OTA-5

## Steps to reproduce

Opening this web page in morph:

```html
<html>

<head></head>
<body>
	<select>
		<option>A</option>
		<option>B</option>
	</select>
</body>
</html>
```
Selecting the select opens the option list a in a new browser window.
The selection of an option works and closes the new instance though

## Expected Behaviour

The option list is shown over the select in the same page

## Actual Behaviour

The option list is opened in a new browser window

**Comment by balcy** [comment]
interesting stackoverflow article 
https://stackoverflow.com/questions/46828303/qt-html-select-tag-dropdown-in-webengineview-shows-up-at-an-unexpected-posi
(that also links to a QT Bug)
I tested the page on BQ Aquaris 4.5, and both landscape and portrait view show the menu in a separate window

**Comment by kugiigi** [comment]
This can be reproduced as well in the OpenStore site when interacting with the dropdowns

**Comment by balcy** [comment]
I've just seen this phenomenon applies to `<input type="date">` as well: the date picker opens in another window, but it works.

**Comment by balcy** [comment]
I don't know how we could solve this in morph, but we can leave it open as known issue of QtWebEngine

**Comment by UniversalSuperBox** [comment]
I discussed this issue with @mariogrip this morning: basically, this is an issue we will need to deal with until we upgrade Mir, since newer versions of Mir have support for drawing "tooltips" as part of your current app's surface.

The most common way people will see this issue is with plain `<input>` boxes for single selection, so we decided that we'll try to make a custom event handler for these which pops up similarly to the link options pane:

![image](https://user-images.githubusercontent.com/21966173/48375156-a56d1700-e68c-11e8-9a13-a2aff061b6d9.png)

**Comment by tv0ll** [comment]
Still getting this error on my OnePlusOne (16.04 Stable). Originally noticed in while in Private Browsing. Selecting from a list would open a new Window (not private). If I do this continually, it will crash the environment and force me to unlock my phone. When selecting from a list in a normal morph window, it will still open a new window, but show my list in very small font to choose from. After selecting my option, it will close the window and update the form with the choice on my previous window.

**Comment by lduboeuf** [comment]
with current devel version  (Nexus 5) , unity reboots after the system tries to open a new window ( dropdown not visible, only splash screen).

**Comment by UniversalSuperBox** [comment]
@lduboeuf, is this on a certain website? Does it occur after a certain set of actions?

**Comment by lduboeuf** [comment]
it happens on github when searching and try to filter later with the dropdown

**Comment by lduboeuf** [comment]
just tested on another website, another wibdow opens but without crashing unity

**Comment by UniversalSuperBox** [comment]
Interesting, this appears to be an issue in Unity and QtMir aggravated by QtWebEngine's inability to keep everything in a single surface.

The Unity8 log reads:

```
[2019-05-22:09:50:50.752] qtmir.surfaces: MirSurface[0x23fcb50,"-"]::updateVisibility(false)
[2019-05-22:09:50:50.753] qtmir.surfaces: MirSurface[0x1f5b238,"morph-browser"]::setLive(false)
[2019-05-22:09:50:50.916] qtmir.surfaces: MirSurface[0x277dec0,"morph-browser"]::updateVisibility(false)
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >'
  what():  Invalid Surface
```

This *is* the same bug, but causing different behavior. It will almost definitely be resolved with the update to Mir 1.1

**Comment by Arc676** [comment]
Any update? Can confirm this still happens using the language selector on Wikipedia on `2019-06-10` on `devel`. Is it already known when the update to the new Mir will be?

**Comment by lduboeuf** [comment]
good news on Edge: no more popup window, but still hard to use

**Comment by lduboeuf** [comment]
![screenshot20191001_222228752](https://user-images.githubusercontent.com/11663835/66077182-bdc57900-e55f-11e9-8694-e5670bed69e5.png)

**Comment by lduboeuf** [comment]
can we close that issue as it is not happening anymore on edge ?

**Comment by Flaburgan** [comment]
The issue changed as with the merge of the new Unity8, a dropdown now appears. However, the issue is now worse than before, as **the dropdown cannot be scrolled** so if there are more than 4-5 options, they can't be selected at all. This should be a blocker for the merge of `devel` in `rc` IMO, as it makes many website unusable. The situation is worse than before.

**Comment by lduboeuf** [comment]
I did a workaround, but still need approbation, here https://github.com/ubports/morph-browser/pull/273

**Comment by UniversalSuperBox** [comment]
Closed by merging new Unity8. The issue then became https://github.com/ubports/morph-browser/issues/239, which has been fixed by https://github.com/ubports/morph-browser/pull/273
